### ISSUE TITLE
ffmpeg build with multi-stage release

### ISSUE THREAD

**Issue by lucemia** [livingbio/FFmpeg#2]
https://medium.com/@Gnaphron/minimalist-multi-stage-container-5a62e08b491d

整理 ffmpeg-gl branch 只保留必要的修改 (don't commit build file)
改使用  docker 來 build ffmpeg, 

Dockerfile

```
From OOXX as ffmpeg
build ffmpeg-gl
...

From GENV
COPY --from=ffmpeg /ffmpeg-binary /ffmpeg
...
```

**Comment by RPing** [comment]
包成 .deb 了 XD
[0.1.0](https://github.com/livingbio/FFmpeg/releases/tag/0.1.0)
我也知道 94cd287 & 174b0c6 挺蠢的
那完全是狗急跳牆下的產物...

**Comment by lucemia** [comment]
@RPing  確認 deb ok 以後可以先 close 此 issue
最近 gcomposer, 相關問題比較多 麻煩優先解決 ffmpeg, gcomposer 相關問題
其他問題可以暫緩處理

**Comment by RPing** [comment]
沒問題
